Manager:
    MDScreen:   #HOME
        id:HomeScreen
        name:'HomeScreen'

        Image:
            source: 'GLSA.png'
            halign: 'center'
            pos_hint: {'center_x': 0.5, 'center_y': 0.87}
        
        MDDivider: #Horizontal Divider
            size_hint_x: 1
            pos_hint: {'center_x': .5, 'center_y': .74}
            color: '#1b1b1b'

        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.5}
            on_release: root.Next("TEST")

            MDButtonIcon:
                icon: 'plus'

            MDButtonText:
                text: 'Begin'

        MDLabel:
            text: 'Home Screen'
            halign: 'center'
            pos_hint: {'center_x': 0.5, 'center_y': 0.08}
            text_color: 'grey'
    
    MDScreen:   #GENRE
        id:GenreScreen
        name:'GenreScreen'

        Image:
            source: 'GLSA.png'
            halign: 'center'
            pos_hint: {'center_x': 0.5, 'center_y': 0.87}

        MDDivider: #Horizontal Divider
            size_hint_x: 1
            pos_hint: {'center_x': .5, 'center_y': .74}
            color: '#1b1b1b'

        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.7}
            on_release: root.Genre("EL")

            MDButtonIcon:
                icon: 'plus'

            MDButtonText:
                text: 'Everyday Life'
        
        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.6}
            on_release: root.Genre("SF")

            MDButtonIcon:
                icon: 'plus'

            MDButtonText:
                text: 'Science Fiction'
        
        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.5}
            on_release: root.Genre("HS")

            MDButtonIcon:
                icon: 'plus'

            MDButtonText:
                text: 'History'

        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.4}
            on_release: root.Genre("FA")

            MDButtonIcon:
                icon: 'plus'

            MDButtonText:
                text: 'Fantasy'

        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.3}
            on_release: root.Genre("HO")

            MDButtonIcon:
                icon: 'plus'

            MDButtonText:
                text: 'Horror'

        MDLabel:
            text: 'Genre Screen'
            halign: 'center'
            pos_hint: {'center_x': 0.5, 'center_y': 0.08}
            text_color: 'grey'

    MDScreen:   #EVERYDAY LIFE TOPIC
        id:ELTopicScreen
        name:'ELTopicScreen'

        Image:
            source: 'GLSA.png'
            halign: 'center'
            pos_hint: {'center_x': 0.5, 'center_y': 0.87}

        MDDivider: #Horizontal Divider
            size_hint_x: 1
            pos_hint: {'center_x': .5, 'center_y': .74}
            color: '#1b1b1b'

        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.7}
            on_release: root.Topic("going on a trip to the mall")

            MDButtonIcon:
                icon: 'store'

            MDButtonText:
                text: 'Trip to the mall'
        
        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.6}
            on_release: root.Topic("a Road Trip")

            MDButtonIcon:
                icon: 'car'

            MDButtonText:
                text: 'Road Trip'
        
        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.5}
            on_release: root.Topic("getting a haircut")

            MDButtonIcon:
                icon: 'hair-dryer'

            MDButtonText:
                text: 'Trip to get a Haircut'

        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.4}
            on_release: root.Topic("going to the movies")

            MDButtonIcon:
                icon: 'movie'

            MDButtonText:
                text: 'Trip to the movies'

        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.3}
            on_release: root.Topic("a person's everyday life")

            MDButtonIcon:
                icon: 'white-balance-sunny'

            MDButtonText:
                text: 'Average Day'

        MDLabel:
            text: 'Everyday Life Stories'
            halign: 'center'
            pos_hint: {'center_x': 0.5, 'center_y': 0.08}
            text_color: 'grey'

    MDScreen:   #SCIENCE FICTION TOPIC
        id:SFTopicScreen
        name:'SFTopicScreen'

        Image:
            source: 'GLSA.png'
            halign: 'center'
            pos_hint: {'center_x': 0.5, 'center_y': 0.87}

        MDDivider: #Horizontal Divider
            size_hint_x: 1
            pos_hint: {'center_x': .5, 'center_y': .74}
            color: '#1b1b1b'

        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.7}
            on_release: root.Topic("a space adventure")

            MDButtonIcon:
                icon: 'rocket'

            MDButtonText:
                text: 'Space Journey'
        
        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.6}
            on_release: root.Topic("time travel")

            MDButtonIcon:
                icon: 'clock-digital'

            MDButtonText:
                text: 'Time Travel'
        
        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.5}
            on_release: root.Topic("a robot uprising")

            MDButtonIcon:
                icon: 'robot-angry'

            MDButtonText:
                text: 'Robot Takeover'

        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.4}
            on_release: root.Topic("a vampire and a werewolf")

            MDButtonIcon:
                icon: 'plus'

            MDButtonText:
                text: 'Vampires & Werewolves'
        
        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.3}
            on_release: root.Topic("an alien abduction")

            MDButtonIcon:
                icon: 'alien'

            MDButtonText:
                text: 'Alien Abduction'

        MDLabel:
            text: 'Science Fiction Stories'
            halign: 'center'
            pos_hint: {'center_x': 0.5, 'center_y': 0.08}
            text_color: 'grey'

    MDScreen:   #HISTORY TOPIC
        id:HSTopicScreen
        name:'HSTopicScreen'

        Image:
            source: 'GLSA.png'
            halign: 'center'
            pos_hint: {'center_x': 0.5, 'center_y': 0.87}

        MDDivider: #Horizontal Divider
            size_hint_x: 1
            pos_hint: {'center_x': .5, 'center_y': .74}
            color: '#1b1b1b'

        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.7}
            on_release: root.Topic("a western adventure")

            MDButtonIcon:
                icon: 'account-cowboy-hat'

            MDButtonText:
                text: 'Western'
        
        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.6}
            on_release: root.Topic("an industrial revolution adventure")

            MDButtonIcon:
                icon: 'factory'

            MDButtonText:
                text: 'Industrial Revolution'
        
        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.5}
            on_release: root.Topic("an adventure in the middle ages")

            MDButtonIcon:
                icon: 'sword-cross'

            MDButtonText:
                text: 'Middle Ages'

        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.4}
            on_release: root.Topic("an adventure during world war II")

            MDButtonIcon:
                icon: 'bomb'

            MDButtonText:
                text: 'World War II'
        
        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.3}
            on_release: root.Topic("an egyptian adventure")

            MDButtonIcon:
                icon: 'pyramid'

            MDButtonText:
                text: 'Ancient Egypt'


        MDLabel:
            text: 'Historical Stories'
            halign: 'center'
            pos_hint: {'center_x': 0.5, 'center_y': 0.08}
            text_color: 'grey'

    MDScreen:   #FANTASY TOPIC
        id:FATopicScreen
        name:'FATopicScreen'

        Image:
            source: 'GLSA.png'
            halign: 'center'
            pos_hint: {'center_x': 0.5, 'center_y': 0.87}

        MDDivider: #Horizontal Divider
            size_hint_x: 1
            pos_hint: {'center_x': .5, 'center_y': .74}
            color: '#1b1b1b'

        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.7}
            on_release: root.Topic("unicorns")

            MDButtonIcon:
                icon: 'unicorn-variant'

            MDButtonText:
                text: 'Unicorns'
        
        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.6}
            on_release: root.Topic("a wizard's adventure")

            MDButtonIcon:
                icon: 'wizard-hat'

            MDButtonText:
                text: 'Witchcraft & Wizardry'
        
        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.5}
            on_release: root.Topic("dragons")

            MDButtonIcon:
                icon: 'fire'

            MDButtonText:
                text: 'Dragons'

        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.4}
            on_release: root.Topic("a heroic quest")

            MDButtonIcon:
                icon: 'sword'

            MDButtonText:
                text: 'Heroic Quest'
        
        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.3}
            on_release: root.Topic("a person who finds themself in a different magical world")

            MDButtonIcon:
                icon: 'google-earth'

            MDButtonText:
                text: 'Brand New World'

        MDLabel:
            text: 'Historical Stories'
            halign: 'center'
            pos_hint: {'center_x': 0.5, 'center_y': 0.08}
            text_color: 'grey'

    MDScreen:   #HORROR TOPIC
        id:HOTopicScreen
        name:'HOTopicScreen'

        Image:
            source: 'GLSA.png'
            halign: 'center'
            pos_hint: {'center_x': 0.5, 'center_y': 0.87}

        MDDivider: #Horizontal Divider
            size_hint_x: 1
            pos_hint: {'center_x': .5, 'center_y': .74}
            color: '#1b1b1b'

        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.7}
            on_release: root.Topic("a haunted doll")

            MDButtonIcon:
                icon: 'baby'

            MDButtonText:
                text: 'Haunted Doll'
        
        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.6}
            on_release: root.Topic("a monster who hunts people down")

            MDButtonIcon:
                icon: 'plus'

            MDButtonText:
                text: 'Monster'
        
        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.5}
            on_release: root.Topic("a haunted house")

            MDButtonIcon:
                icon: 'home-alert'

            MDButtonText:
                text: 'Haunted House'
        
        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.4}
            on_release: root.Topic("a killer on the loose")

            MDButtonIcon:
                icon: 'knife'

            MDButtonText:
                text: 'Serial Killer'
        
        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.3}
            on_release: root.Topic("ghosts")

            MDButtonIcon:
                icon: 'ghost'

            MDButtonText:
                text: 'Ghosts'


        MDLabel:
            text: 'Historical Stories'
            halign: 'center'
            pos_hint: {'center_x': 0.5, 'center_y': 0.08}
            text_color: 'grey'

    MDScreen:   #LANGUGAE
        id:LanguageScreen
        name:'LanguageScreen'

        Image:
            source: 'GLSA.png'
            halign: 'center'
            pos_hint: {'center_x': 0.5, 'center_y': 0.87}

        MDDivider: #Horizontal Divider
            size_hint_x: 1
            pos_hint: {'center_x': .5, 'center_y': .74}
            color: '#1b1b1b'


            
        MDBoxLayout:
            id: main_scroll
            orientation: "vertical"
            spacing: 30
            adaptive_height: True
            pos_hint: {'center_x': .5, 'center_y': .45}

            MDButton:
                pos_hint: {'center_x': 0.5, 'center_y': 0.7}
                on_release: root.Language("French")

                MDButtonIcon:
                    icon: 'plus'

                MDButtonText:
                    text: 'French'

            MDButton:
                pos_hint: {'center_x': 0.5, 'center_y': 0.6}
                on_release: root.Language("Spanish")

                MDButtonIcon:
                    icon: 'plus'

                MDButtonText:
                    text: 'Spanish'

            MDButton:
                pos_hint: {'center_x': 0.5, 'center_y': 0.5}
                on_release: root.Language("German")

                MDButtonIcon:
                    icon: 'plus'

                MDButtonText:
                    text: 'German'

            MDButton:
                pos_hint: {'center_x': 0.5, 'center_y': 0.4}
                on_release: root.Language("Portuguese")

                MDButtonIcon:
                    icon: 'plus'

                MDButtonText:
                    text: 'Portuguese'

            MDButton:
                pos_hint: {'center_x': 0.5, 'center_y': 0.3}
                on_release: root.Language("Japanese")

                MDButtonIcon:
                    icon: 'plus'

                MDButtonText:
                    text: 'Japanese'

            MDButton:
                pos_hint: {'center_x': 0.5, 'center_y': 0.3}
                on_release: root.Language("Chinese")

                MDButtonIcon:
                    icon: 'plus'

                MDButtonText:
                    text: 'Chinese (Mandarin)'

            MDButton:
                pos_hint: {'center_x': 0.5, 'center_y': 0.3}
                on_release: root.Language("Italian")

                MDButtonIcon:
                    icon: 'plus'

                MDButtonText:
                    text: 'Italian'

        MDLabel:
            text: 'Language Screen'
            halign: 'center'
            pos_hint: {'center_x': 0.5, 'center_y': 0.08}
            text_color: 'grey'
    
    MDScreen:   #DIFFICULTY
        id:DifficultyScreen
        name:'DifficultyScreen'

        Image:
            source: 'GLSA.png'
            halign: 'center'
            pos_hint: {'center_x': 0.5, 'center_y': 0.87}

        MDDivider: #Horizontal Divider
            size_hint_x: 1
            pos_hint: {'center_x': .5, 'center_y': .74}
            color: '#1b1b1b'
                
        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.6}
            on_release: root.Difficulty(1)

            MDButtonIcon:
                icon: 'plus'

            MDButtonText:
                text: 'Easy'

        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.5}
            on_release: root.Difficulty(2)

            MDButtonIcon:
                icon: 'plus'

            MDButtonText:
                text: 'Medium'

        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.4}
            on_release: root.Difficulty(3)

            MDButtonIcon:
                icon: 'plus'

            MDButtonText:
                text: 'Hard'

        MDLabel:
            text: 'Difficulty Screen'
            halign: 'center'
            pos_hint: {'center_x': 0.5, 'center_y': 0.08}
            text_color: 'grey'

    MDScreen:   #PROMPT
        id:PromptScreen
        name:'PromptScreen'

        MDLabel:
            id: prompt_output
            text: "L"
            halign: 'center'
            pos_hint: {'center_x': 0.5, 'center_y': 0.85}
            text_color: '#6183e2'
            size_hint_x: 0.95

        MDDivider: #Horizontal Divider
            size_hint_x: 1
            pos_hint: {'center_x': .5, 'center_y': 0.6}
            color: '#1b1b1b'

        MDBoxLayout:
            id: main_scroll
            orientation: "vertical"
            spacing: 25
            adaptive_height: True
            pos_hint: {'center_x': .5, 'center_y': .4}

            MDLabel:
                id: question_output1
                text: "L"
                halign: 'center'
                pos_hint: {'center_x': 0.5, 'center_y': 0.5}
                text_color: '#6183e2'
                size_hint_x: 0.95

            MDTextField: #TextField 1
                mode: "outlined"
                pos_hint: {'center_x': 0.5, 'center_y': 0.35}
                size_hint_x: 0.8

                MDTextFieldLeadingIcon:
                    icon: "numeric-1"

            MDLabel:
                id: question_output2
                text: "L"
                halign: 'center'
                pos_hint: {'center_x': 0.5, 'center_y': 0.5}
                text_color: '#6183e2'
                size_hint_x: 0.95

            MDTextField: #TextField 2
                mode: "outlined"
                pos_hint: {'center_x': 0.5, 'center_y': 0.30}
                size_hint_x: 0.8

                MDTextFieldLeadingIcon:
                    icon: "numeric-2"


            MDLabel:
                id: question_output3
                text: "L"
                halign: 'center'
                pos_hint: {'center_x': 0.5, 'center_y': 0.5}
                text_color: '#6183e2'
                size_hint_x: 0.95

            MDTextField: #TextField 3
                mode: "outlined"
                pos_hint: {'center_x': 0.5, 'center_y': 0.25}
                size_hint_x: 0.8

                MDTextFieldLeadingIcon:
                    icon: "numeric-3"


            MDLabel:
                id: question_output4
                text: "L"
                halign: 'center'
                pos_hint: {'center_x': 0.5, 'center_y': 0.5}
                text_color: '#6183e2'
                size_hint_x: 0.95

            MDTextField: #TextField 4
                mode: "outlined"
                pos_hint: {'center_x': 0.5, 'center_y': 0.20}
                size_hint_x: 0.8

                MDTextFieldLeadingIcon:
                    icon: "numeric-4"


            MDLabel:
                id: question_output5
                text: "L"
                halign: 'center'
                pos_hint: {'center_x': 0.5, 'center_y': 0.5}
                text_color: '#6183e2'
                size_hint_x: 0.95

            MDTextField: #TextField 5
                mode: "outlined"
                pos_hint: {'center_x': 0.5, 'center_y': 0.15}
                size_hint_x: 0.8

                MDTextFieldLeadingIcon:
                    icon: "numeric-5"


        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.05}
            on_release: root.PlayPrompt()

            MDButtonIcon:
                icon: 'play'

            MDButtonText:
                text: 'Play Audio'
