<HomeScreen>:
    MDLabel:
        text: 'Home Screen'
        halign: 'center'
        pos_hint: {'center_x': 0.5, 'center_y': 0.9}
        text_color: 'purple'

    MDButton:
        pos_hint: {'center_x': 0.5, 'center_y': 0.5}
        on_release: root.Next("TEST")

        MDButtonIcon:
            icon: 'plus'

        MDButtonText:
            text: 'Go to next screen'
        
<GenreScreen>:
    MDLabel:
        text: 'Genre Screen'
        halign: 'center'
        pos_hint: {'center_x': 0.5, 'center_y': 0.9}
        text_color: 'purple'
        
    MDButton:
        pos_hint: {'center_x': 0.5, 'center_y': 0.7}
        on_release: root.Next("a Space adventure")

        MDButtonIcon:
            icon: 'plus'

        MDButtonText:
            text: 'Space Adventure'
    
    MDButton:
        pos_hint: {'center_x': 0.5, 'center_y': 0.6}
        on_release: root.Next("a Road Trip")

        MDButtonIcon:
            icon: 'plus'

        MDButtonText:
            text: 'Road Trip'
    
    MDButton:
        pos_hint: {'center_x': 0.5, 'center_y': 0.5}
        on_release: root.Next("a video game")

        MDButtonIcon:
            icon: 'plus'

        MDButtonText:
            text: 'Video Game'

<LanguageScreen>:
    MDLabel:
        text: 'Language Screen'
        halign: 'center'
        pos_hint: {'center_x': 0.5, 'center_y': 0.9}
        text_color: 'purple'
        
    MDButton:
        pos_hint: {'center_x': 0.5, 'center_y': 0.7}
        on_release: root.Next("French")

        MDButtonIcon:
            icon: 'plus'

        MDButtonText:
            text: 'French'

    MDButton:
        pos_hint: {'center_x': 0.5, 'center_y': 0.6}
        on_release: root.Next("Spanish")

        MDButtonIcon:
            icon: 'plus'

        MDButtonText:
            text: 'Spanish'

    MDButton:
        pos_hint: {'center_x': 0.5, 'center_y': 0.5}
        on_release: root.Next("German")

        MDButtonIcon:
            icon: 'plus'

        MDButtonText:
            text: 'German'

    MDButton:
        pos_hint: {'center_x': 0.5, 'center_y': 0.4}
        on_release: root.Next("Portuguese")

        MDButtonIcon:
            icon: 'plus'

        MDButtonText:
            text: 'Portuguese'

    MDButton:
        pos_hint: {'center_x': 0.5, 'center_y': 0.3}
        on_release: root.Next("Japanese")

        MDButtonIcon:
            icon: 'plus'

        MDButtonText:
            text: 'Japanese'


<DifficultyScreen>:
    MDLabel:
        text: 'Difficulty Screen'
        halign: 'center'
        pos_hint: {'center_x': 0.5, 'center_y': 0.9}
        text_color: 'purple'
            
    MDButton:
        pos_hint: {'center_x': 0.5, 'center_y': 0.6}
        on_release: root.Next(1)

        MDButtonIcon:
            icon: 'plus'

        MDButtonText:
            text: 'Easy'

    MDButton:
        pos_hint: {'center_x': 0.5, 'center_y': 0.5}
        on_release: root.Next(2)

        MDButtonIcon:
            icon: 'plus'

        MDButtonText:
            text: 'Medium'

    MDButton:
        pos_hint: {'center_x': 0.5, 'center_y': 0.4}
        on_release: root.Next(3)

        MDButtonIcon:
            icon: 'plus'

        MDButtonText:
            text: 'Hard'


<PromptScreen>:
    MDLabel:
        text: root.response
        halign: 'center'
        pos_hint: {'center_x': 0.5, 'center_y': 0.9}
        text_color: 'purple'