Manager:
    MDScreen:   #HOME
        id:HomeScreen
        name:'HomeScreen'

        Image:
            source: 'GLSA.png'
            halign: 'center'
            pos_hint: {'center_x': 0.5, 'center_y': 0.87}
        
        MDDivider: #Horizontal Divider
            size_hint_x: 1
            pos_hint: {'center_x': .5, 'center_y': .74}
            color: '#1b1b1b'

        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.5}
            on_release: root.Next("TEST")

            MDButtonIcon:
                icon: 'plus'

            MDButtonText:
                text: 'Go to next screen'

        MDLabel:
            text: 'Home Screen'
            halign: 'center'
            pos_hint: {'center_x': 0.5, 'center_y': 0.08}
            text_color: 'grey'
    
    MDScreen:   #GENRE
        id:GenreScreen
        name:'GenreScreen'

        Image:
            source: 'GLSA.png'
            halign: 'center'
            pos_hint: {'center_x': 0.5, 'center_y': 0.87}

        MDDivider: #Horizontal Divider
            size_hint_x: 1
            pos_hint: {'center_x': .5, 'center_y': .74}
            color: '#1b1b1b'

        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.5}
            on_release: root.Genre("EL")

            MDButtonIcon:
                icon: 'plus'

            MDButtonText:
                text: 'Everyday Life'
        
        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.4}
            on_release: root.Genre("SF")

            MDButtonIcon:
                icon: 'plus'

            MDButtonText:
                text: 'Science Fiction'
        
        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.3}
            on_release: root.Genre("HS")

            MDButtonIcon:
                icon: 'plus'

            MDButtonText:
                text: 'History'

        MDLabel:
            text: 'Genre Screen'
            halign: 'center'
            pos_hint: {'center_x': 0.5, 'center_y': 0.08}
            text_color: 'grey'

    MDScreen:   #EVERYDAY LIFE TOPIC
        id:ELTopicScreen
        name:'ELTopicScreen'

        Image:
            source: 'GLSA.png'
            halign: 'center'
            pos_hint: {'center_x': 0.5, 'center_y': 0.87}

        MDDivider: #Horizontal Divider
            size_hint_x: 1
            pos_hint: {'center_x': .5, 'center_y': .74}
            color: '#1b1b1b'

        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.5}
            on_release: root.Genre("going on a trip to the mall")

            MDButtonIcon:
                icon: 'plus'

            MDButtonText:
                text: 'Trip to the mall'
        
        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.4}
            on_release: root.Genre("a Road Trip")

            MDButtonIcon:
                icon: 'plus'

            MDButtonText:
                text: 'Road Trip'
        
        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.3}
            on_release: root.Genre("getting a haircut")

            MDButtonIcon:
                icon: 'plus'

            MDButtonText:
                text: 'Trip to get a Haircut'

        MDLabel:
            text: 'Everyday Life Stories'
            halign: 'center'
            pos_hint: {'center_x': 0.5, 'center_y': 0.08}
            text_color: 'grey'

    MDScreen:   #SCIENCE FICTION TOPIC
        id:SFTopicScreen
        name:'SFTopicScreen'

        Image:
            source: 'GLSA.png'
            halign: 'center'
            pos_hint: {'center_x': 0.5, 'center_y': 0.87}

        MDDivider: #Horizontal Divider
            size_hint_x: 1
            pos_hint: {'center_x': .5, 'center_y': .74}
            color: '#1b1b1b'

        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.5}
            on_release: root.Genre("a space adventure")

            MDButtonIcon:
                icon: 'plus'

            MDButtonText:
                text: 'Space Journey'
        
        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.4}
            on_release: root.Genre("time travel")

            MDButtonIcon:
                icon: 'plus'

            MDButtonText:
                text: 'Time Travel'
        
        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.3}
            on_release: root.Genre("a robot uprising")

            MDButtonIcon:
                icon: 'plus'

            MDButtonText:
                text: 'Robot Takeover'

        MDLabel:
            text: 'Science Fiction Stories'
            halign: 'center'
            pos_hint: {'center_x': 0.5, 'center_y': 0.08}
            text_color: 'grey'

    MDScreen:   #HISTORY TOPIC
        id:HSTopicScreen
        name:'HSTopicScreen'

        Image:
            source: 'GLSA.png'
            halign: 'center'
            pos_hint: {'center_x': 0.5, 'center_y': 0.87}

        MDDivider: #Horizontal Divider
            size_hint_x: 1
            pos_hint: {'center_x': .5, 'center_y': .74}
            color: '#1b1b1b'

        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.5}
            on_release: root.Genre("a western adventure")

            MDButtonIcon:
                icon: 'plus'

            MDButtonText:
                text: 'Western'
        
        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.4}
            on_release: root.Genre("an industrial revolution adventure")

            MDButtonIcon:
                icon: 'plus'

            MDButtonText:
                text: 'Industrial Revolution'
        
        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.3}
            on_release: root.Genre("an egyptian adventure")

            MDButtonIcon:
                icon: 'plus'

            MDButtonText:
                text: 'Ancient Egypt'

        MDLabel:
            text: 'Historical Stories'
            halign: 'center'
            pos_hint: {'center_x': 0.5, 'center_y': 0.08}
            text_color: 'grey'

    MDScreen:   #LANGUGAE
        id:LanguageScreen
        name:'LanguageScreen'

        Image:
            source: 'GLSA.png'
            halign: 'center'
            pos_hint: {'center_x': 0.5, 'center_y': 0.87}

        MDDivider: #Horizontal Divider
            size_hint_x: 1
            pos_hint: {'center_x': .5, 'center_y': .74}
            color: '#1b1b1b'

        ScrollView:
            do_scroll_x: False
            do_scroll_y: True
            pos_hint: {'center_x': .5, 'center_y': .1}
            
            MDBoxLayout:
                id: main_scroll
                orientation: "vertical"
                spacing: 20
                adaptive_height: True
                pos_hint: {'center_x': .5, 'center_y': .5}

                MDButton:
                    pos_hint: {'center_x': 0.5, 'center_y': 0.7}
                    on_release: root.Language("French")

                    MDButtonIcon:
                        icon: 'plus'

                    MDButtonText:
                        text: 'French'

                MDButton:
                    pos_hint: {'center_x': 0.5, 'center_y': 0.6}
                    on_release: root.Language("Spanish")

                    MDButtonIcon:
                        icon: 'plus'

                    MDButtonText:
                        text: 'Spanish'

                MDButton:
                    pos_hint: {'center_x': 0.5, 'center_y': 0.5}
                    on_release: root.Language("German")

                    MDButtonIcon:
                        icon: 'plus'

                    MDButtonText:
                        text: 'German'

                MDButton:
                    pos_hint: {'center_x': 0.5, 'center_y': 0.4}
                    on_release: root.Language("Portuguese")

                    MDButtonIcon:
                        icon: 'plus'

                    MDButtonText:
                        text: 'Portuguese'

                MDButton:
                    pos_hint: {'center_x': 0.5, 'center_y': 0.3}
                    on_release: root.Language("Japanese")

                    MDButtonIcon:
                        icon: 'plus'

                    MDButtonText:
                        text: 'Japanese'

        MDLabel:
            text: 'Language Screen'
            halign: 'center'
            pos_hint: {'center_x': 0.5, 'center_y': 0.08}
            text_color: 'grey'
    
    MDScreen:   #DIFFICULTY
        id:DifficultyScreen
        name:'DifficultyScreen'

        Image:
            source: 'GLSA.png'
            halign: 'center'
            pos_hint: {'center_x': 0.5, 'center_y': 0.87}

        MDDivider: #Horizontal Divider
            size_hint_x: 1
            pos_hint: {'center_x': .5, 'center_y': .74}
            color: '#1b1b1b'
                
        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.6}
            on_release: root.Difficulty(1)

            MDButtonIcon:
                icon: 'plus'

            MDButtonText:
                text: 'Easy'

        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.5}
            on_release: root.Difficulty(2)

            MDButtonIcon:
                icon: 'plus'

            MDButtonText:
                text: 'Medium'

        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.4}
            on_release: root.Difficulty(3)

            MDButtonIcon:
                icon: 'plus'

            MDButtonText:
                text: 'Hard'

        MDLabel:
            text: 'Difficulty Screen'
            halign: 'center'
            pos_hint: {'center_x': 0.5, 'center_y': 0.08}
            text_color: 'grey'

    MDScreen:   #PROMPT
        id:PromptScreen
        name:'PromptScreen'
        MDLabel:
            id: prompt_output
            text: root.response
            halign: 'center'
            pos_hint: {'center_x': 0.5, 'center_y': 0.5}
            text_color: 'yellow'    