Manager:

    MDScreen:   #HOME
        id:HomeScreen
        name:'HomeScreen'

        Image:
            source: 'GLSA.png'
            halign: 'center'
            pos_hint: {'center_x': 0.5, 'center_y': 0.87}
        
        MDDivider: #Horizontal Divider
            size_hint_x: 1
            pos_hint: {'center_x': .5, 'center_y': .74}
            color: '#1b1b1b'

        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.5}
            on_release: root.Next()

            MDButtonIcon:
                icon: 'plus'

            MDButtonText:
                text: 'Begin' 
                font_name: 'Code2000'

        MDLabel:
            text: 'Home Screen'
            halign: 'center'
            pos_hint: {'center_x': 0.5, 'center_y': 0.08}
            text_color: 'grey'
    
    MDScreen:   #SETTINGS
        id:SettingsScreen
        name:'SettingsScreen'

        Image:
            source: 'GLSA.png'
            halign: 'center'
            pos_hint: {'center_x': 0.5, 'center_y': 0.87}
        
        MDDivider: #Horizontal Divider
            size_hint_x: 1
            pos_hint: {'center_x': .5, 'center_y': .74}
            color: '#1b1b1b'

        MDTextField:
            id: KeyText
            size_hint: .6, .3
            mode: "outlined"
            pos_hint: {'center_x': .375, 'center_y': .5}

            MDTextFieldHintText:
                text: "Gemini API Key"

            MDTextFieldHelperText:
                id: KeyValidity
                text: "N/A"
                mode: "persistent"
                text_color_normal: "red"

            MDTextFieldMaxLengthText:
                max_text_length: 40

        MDIconButton:
            pos_hint: {'center_x': 0.8, 'center_y': 0.5}
            icon: "check-bold"
            on_release: root.CheckKey()
                
        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.3}
            on_release: root.ContinueSettings()
            
            MDButtonText:
                text: 'Continue'


        MDLabel:
            text: 'Settings Screen'
            halign: 'center'
            pos_hint: {'center_x': 0.5, 'center_y': 0.08}
            text_color: 'grey'
    
    MDScreen:   #GENRE
        id:GenreScreen
        name:'GenreScreen'

        Image:
            source: 'GLSA.png'
            halign: 'center'
            pos_hint: {'center_x': 0.5, 'center_y': 0.87}

        MDDivider: #Horizontal Divider
            size_hint_x: 1
            pos_hint: {'center_x': .5, 'center_y': .74}
            color: '#1b1b1b'

        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.7}
            on_release: root.Genre("EL")

            MDButtonIcon:
                icon: 'plus'

            MDButtonText:
                text: 'Everyday Life'
        
        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.6}
            on_release: root.Genre("SF")

            MDButtonIcon:
                icon: 'plus'

            MDButtonText:
                text: 'Science Fiction'
        
        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.5}
            on_release: root.Genre("HS")

            MDButtonIcon:
                icon: 'plus'

            MDButtonText:
                text: 'History'

        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.4}
            on_release: root.Genre("FA")

            MDButtonIcon:
                icon: 'plus'

            MDButtonText:
                text: 'Fantasy'

        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.3}
            on_release: root.Genre("HO")

            MDButtonIcon:
                icon: 'plus'

            MDButtonText:
                text: 'Horror'

        MDLabel:
            text: 'Genre Screen'
            halign: 'center'
            pos_hint: {'center_x': 0.5, 'center_y': 0.08}
            text_color: 'grey'

    MDScreen:   #EVERYDAY LIFE TOPIC
        id:ELTopicScreen
        name:'ELTopicScreen'

        Image:
            source: 'GLSA.png'
            halign: 'center'
            pos_hint: {'center_x': 0.5, 'center_y': 0.87}

        MDDivider: #Horizontal Divider
            size_hint_x: 1
            pos_hint: {'center_x': .5, 'center_y': .74}
            color: '#1b1b1b'

        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.7}
            on_release: root.Topic("going on a trip to the mall")

            MDButtonIcon:
                icon: 'store'

            MDButtonText:
                text: 'Trip to the mall'
        
        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.6}
            on_release: root.Topic("a Road Trip")

            MDButtonIcon:
                icon: 'car'

            MDButtonText:
                text: 'Road Trip'
        
        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.5}
            on_release: root.Topic("getting a haircut")

            MDButtonIcon:
                icon: 'hair-dryer'

            MDButtonText:
                text: 'Trip to get a Haircut'

        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.4}
            on_release: root.Topic("going to the movies")

            MDButtonIcon:
                icon: 'movie'

            MDButtonText:
                text: 'Trip to the movies'

        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.3}
            on_release: root.Topic("a person's everyday life")

            MDButtonIcon:
                icon: 'white-balance-sunny'

            MDButtonText:
                text: 'Average Day'

        MDLabel:
            text: 'Everyday Life Stories'
            halign: 'center'
            pos_hint: {'center_x': 0.5, 'center_y': 0.08}
            text_color: 'grey'

        MDButton:
            pos_hint: {'center_x': 0.1, 'center_y': 0.075}
            on_release: root.BackTo("GenreScreen")

            MDButtonIcon:
                icon: 'chevron-left'

    MDScreen:   #SCIENCE FICTION TOPIC
        id:SFTopicScreen
        name:'SFTopicScreen'

        Image:
            source: 'GLSA.png'
            halign: 'center'
            pos_hint: {'center_x': 0.5, 'center_y': 0.87}

        MDDivider: #Horizontal Divider
            size_hint_x: 1
            pos_hint: {'center_x': .5, 'center_y': .74}
            color: '#1b1b1b'

        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.7}
            on_release: root.Topic("a space adventure")

            MDButtonIcon:
                icon: 'rocket'

            MDButtonText:
                text: 'Space Journey'
        
        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.6}
            on_release: root.Topic("time travel")

            MDButtonIcon:
                icon: 'clock-digital'

            MDButtonText:
                text: 'Time Travel'
        
        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.5}
            on_release: root.Topic("a robot uprising")

            MDButtonIcon:
                icon: 'robot-angry'

            MDButtonText:
                text: 'Robot Takeover'

        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.4}
            on_release: root.Topic("a vampire and a werewolf")

            MDButtonIcon:
                icon: 'plus'

            MDButtonText:
                text: 'Vampires & Werewolves'
        
        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.3}
            on_release: root.Topic("an alien abduction")

            MDButtonIcon:
                icon: 'alien'

            MDButtonText:
                text: 'Alien Abduction'

        MDLabel:
            text: 'Science Fiction Stories'
            halign: 'center'
            pos_hint: {'center_x': 0.5, 'center_y': 0.08}
            text_color: 'grey'

        MDButton:
            pos_hint: {'center_x': 0.1, 'center_y': 0.075}
            on_release: root.BackTo("GenreScreen")

            MDButtonIcon:
                icon: 'chevron-left'

    MDScreen:   #HISTORY TOPIC
        id:HSTopicScreen
        name:'HSTopicScreen'

        Image:
            source: 'GLSA.png'
            halign: 'center'
            pos_hint: {'center_x': 0.5, 'center_y': 0.87}

        MDDivider: #Horizontal Divider
            size_hint_x: 1
            pos_hint: {'center_x': .5, 'center_y': .74}
            color: '#1b1b1b'

        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.7}
            on_release: root.Topic("a western adventure")

            MDButtonIcon:
                icon: 'account-cowboy-hat'

            MDButtonText:
                text: 'Western'
        
        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.6}
            on_release: root.Topic("an industrial revolution adventure")

            MDButtonIcon:
                icon: 'factory'

            MDButtonText:
                text: 'Industrial Revolution'
        
        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.5}
            on_release: root.Topic("an adventure in the middle ages")

            MDButtonIcon:
                icon: 'sword-cross'

            MDButtonText:
                text: 'Middle Ages'

        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.4}
            on_release: root.Topic("an adventure during world war II")

            MDButtonIcon:
                icon: 'bomb'

            MDButtonText:
                text: 'World War II'
        
        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.3}
            on_release: root.Topic("an egyptian adventure")

            MDButtonIcon:
                icon: 'pyramid'

            MDButtonText:
                text: 'Ancient Egypt'


        MDLabel:
            text: 'Historical Stories'
            halign: 'center'
            pos_hint: {'center_x': 0.5, 'center_y': 0.08}
            text_color: 'grey'


        MDButton:
            pos_hint: {'center_x': 0.1, 'center_y': 0.075}
            on_release: root.BackTo("GenreScreen")

            MDButtonIcon:
                icon: 'chevron-left'

    MDScreen:   #FANTASY TOPIC
        id:FATopicScreen
        name:'FATopicScreen'

        Image:
            source: 'GLSA.png'
            halign: 'center'
            pos_hint: {'center_x': 0.5, 'center_y': 0.87}

        MDDivider: #Horizontal Divider
            size_hint_x: 1
            pos_hint: {'center_x': .5, 'center_y': .74}
            color: '#1b1b1b'

        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.7}
            on_release: root.Topic("unicorns")

            MDButtonIcon:
                icon: 'unicorn-variant'

            MDButtonText:
                text: 'Unicorns'
        
        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.6}
            on_release: root.Topic("a wizard's adventure")

            MDButtonIcon:
                icon: 'wizard-hat'

            MDButtonText:
                text: 'Witchcraft & Wizardry'
        
        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.5}
            on_release: root.Topic("dragons")

            MDButtonIcon:
                icon: 'fire'

            MDButtonText:
                text: 'Dragons'

        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.4}
            on_release: root.Topic("a heroic quest")

            MDButtonIcon:
                icon: 'sword'

            MDButtonText:
                text: 'Heroic Quest'
        
        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.3}
            on_release: root.Topic("a person who finds themself in a different magical world")

            MDButtonIcon:
                icon: 'google-earth'

            MDButtonText:
                text: 'Brand New World'

        MDLabel:
            text: 'Historical Stories'
            halign: 'center'
            pos_hint: {'center_x': 0.5, 'center_y': 0.08}
            text_color: 'grey'


        MDButton:
            pos_hint: {'center_x': 0.1, 'center_y': 0.075}
            on_release: root.BackTo("GenreScreen")

            MDButtonIcon:
                icon: 'chevron-left'

    MDScreen:   #HORROR TOPIC
        id:HOTopicScreen
        name:'HOTopicScreen'

        Image:
            source: 'GLSA.png'
            halign: 'center'
            pos_hint: {'center_x': 0.5, 'center_y': 0.87}

        MDDivider: #Horizontal Divider
            size_hint_x: 1
            pos_hint: {'center_x': .5, 'center_y': .74}
            color: '#1b1b1b'

        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.7}
            on_release: root.Topic("a haunted doll")

            MDButtonIcon:
                icon: 'baby'

            MDButtonText:
                text: 'Haunted Doll'
        
        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.6}
            on_release: root.Topic("a monster who hunts people down")

            MDButtonIcon:
                icon: 'plus'

            MDButtonText:
                text: 'Monster'
        
        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.5}
            on_release: root.Topic("a haunted house")

            MDButtonIcon:
                icon: 'home-alert'

            MDButtonText:
                text: 'Haunted House'
        
        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.4}
            on_release: root.Topic("a killer on the loose")

            MDButtonIcon:
                icon: 'knife'

            MDButtonText:
                text: 'Serial Killer'
        
        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.3}
            on_release: root.Topic("ghosts")

            MDButtonIcon:
                icon: 'ghost'

            MDButtonText:
                text: 'Ghosts'


        MDLabel:
            text: 'Historical Stories'
            halign: 'center'
            pos_hint: {'center_x': 0.5, 'center_y': 0.08}
            text_color: 'grey'


        MDButton:
            pos_hint: {'center_x': 0.1, 'center_y': 0.075}
            on_release: root.BackTo("GenreScreen")

            MDButtonIcon:
                icon: 'chevron-left'

    MDScreen:   #LANGUGAE
        id:LanguageScreen
        name:'LanguageScreen'

        Image:
            source: 'GLSA.png'
            halign: 'center'
            pos_hint: {'center_x': 0.5, 'center_y': 0.87}

        MDDivider: #Horizontal Divider
            size_hint_x: 1
            pos_hint: {'center_x': .5, 'center_y': .74}
            color: '#1b1b1b'


            
        MDBoxLayout:
            id: main_scroll
            orientation: "vertical"
            spacing: 30
            adaptive_height: True
            pos_hint: {'center_x': .5, 'center_y': .45}

            MDButton:
                pos_hint: {'center_x': 0.5, 'center_y': 0.8}
                on_release: root.Language("English")

                MDButtonIcon:
                    icon: 'plus'

                MDButtonText:
                    text: 'English'


            MDButton:
                pos_hint: {'center_x': 0.5, 'center_y': 0.7}
                on_release: root.Language("French")

                MDButtonIcon:
                    icon: 'plus'

                MDButtonText:
                    text: 'French'

            MDButton:
                pos_hint: {'center_x': 0.5, 'center_y': 0.6}
                on_release: root.Language("Spanish")

                MDButtonIcon:
                    icon: 'plus'

                MDButtonText:
                    text: 'Spanish'

            MDButton:
                pos_hint: {'center_x': 0.5, 'center_y': 0.5}
                on_release: root.Language("German")

                MDButtonIcon:
                    icon: 'plus'

                MDButtonText:
                    text: 'German'

            MDButton:
                pos_hint: {'center_x': 0.5, 'center_y': 0.4}
                on_release: root.Language("Portuguese")

                MDButtonIcon:
                    icon: 'plus'

                MDButtonText:
                    text: 'Portuguese'

            MDButton:
                pos_hint: {'center_x': 0.5, 'center_y': 0.3}
                on_release: root.Language("Japanese")

                MDButtonIcon:
                    icon: 'plus'

                MDButtonText:
                    text: 'Japanese'

            MDButton:
                pos_hint: {'center_x': 0.5, 'center_y': 0.3}
                on_release: root.Language("Chinese")

                MDButtonIcon:
                    icon: 'plus'

                MDButtonText:
                    text: 'Chinese (Mandarin)'

            MDButton:
                pos_hint: {'center_x': 0.5, 'center_y': 0.3}
                on_release: root.Language("Italian")

                MDButtonIcon:
                    icon: 'plus'

                MDButtonText:
                    text: 'Italian'

        MDLabel:
            text: 'Language Screen'
            halign: 'center'
            pos_hint: {'center_x': 0.5, 'center_y': 0.08}
            text_color: 'grey'

        MDButton:
            pos_hint: {'center_x': 0.1, 'center_y': 0.075}
            on_release: root.BackTo("Topic")

            MDButtonIcon:
                icon: 'chevron-left'
    
    MDScreen:   #DIFFICULTY
        id:DifficultyScreen
        name:'DifficultyScreen'

        Image:
            source: 'GLSA.png'
            halign: 'center'
            pos_hint: {'center_x': 0.5, 'center_y': 0.87}

        MDDivider: #Horizontal Divider
            size_hint_x: 1
            pos_hint: {'center_x': .5, 'center_y': .74}
            color: '#1b1b1b'

        MDCard:
            pos_hint: {'center_x': 0.5, 'center_y': 0.62}
            orientation: "vertical"
            style: "filled"
            padding: "4dp"
            size_hint: None, None
            size: "200dp", "170dp"
            on_release: root.Difficulty(1)

            Image:
                source: 'easy.png'
                halign: 'center'
                pos_hint: {'center_y': 0.7}

            MDLabel:
                text: "Story is in chosen language and questions are in default language"
                halign: 'center'
                pos_hint: {'center_x': 0.5, 'center_y': 0.6}
                text_color: 'white'

        MDCard:
            pos_hint: {'center_x': 0.5, 'center_y': 0.4}
            orientation: "vertical"
            style: "filled"
            padding: "4dp"
            size_hint: None, None
            size: "200dp", "170dp"
            on_release: root.Difficulty(2)

            Image:
                source: 'medium.png'
                halign: 'center'
                pos_hint: {'center_y': 0.7}

            MDLabel:
                text: "Story is in chosen language and questions are in chosen language"
                halign: 'center'
                pos_hint: {'center_x': 0.5, 'center_y': 0.6}
                text_color: 'white'

        MDCard:
            pos_hint: {'center_x': 0.5, 'center_y': 0.18}
            orientation: "vertical"
            style: "filled"
            padding: "4dp"
            size_hint: None, None
            size: "200dp", "170dp"
            on_release: root.Difficulty(3)

            Image:
                source: 'hard.png'
                halign: 'center'
                pos_hint: {'center_y': 0.7}

            MDLabel:
                text: "Story, questions and answer given must all be in chosen language"
                halign: 'center'
                pos_hint: {'center_x': 0.5, 'center_y': 0.6}
                text_color: 'white'    

        # MDButton:
        #     pos_hint: {'center_x': 0.5, 'center_y': 0.6}
        #     on_release: root.Difficulty(1)

        #     MDButtonIcon:
        #         icon: 'plus'

        #     MDButtonText:
        #         text: 'Easy'

        # MDButton:
        #     pos_hint: {'center_x': 0.5, 'center_y': 0.5}
        #     on_release: root.Difficulty(2)

        #     MDButtonIcon:
        #         icon: 'plus'

        #     MDButtonText:
        #         text: 'Medium'

        # MDButton:
        #     pos_hint: {'center_x': 0.5, 'center_y': 0.4}
        #     on_release: root.Difficulty(3)

        #    MDButtonIcon:
        #        icon: 'plus'

        #    MDButtonText:
        #        text: 'Hard'

        MDLabel:
            text: 'Difficulty Screen'
            halign: 'center'
            pos_hint: {'center_x': 0.5, 'center_y': 0.03}
            text_color: 'grey'

        MDButton:
            pos_hint: {'center_x': 0.1, 'center_y': 0.075}
            on_release: root.BackTo("LanguageScreen")

            MDButtonIcon:
                icon: 'chevron-left'

    MDScreen:   #PROMPT
        id:PromptScreen
        name:'PromptScreen'

        MDLabel:
            id: prompt_output
            font_name: 'Code2000'
            text: "L"
            halign: 'center'
            pos_hint: {'center_x': 0.5, 'center_y': 0.85}
            text_color: '#6183e2'
            size_hint_x: 0.95

        MDDivider: #Horizontal Divider
            size_hint_x: 1
            pos_hint: {'center_x': .5, 'center_y': 0.6}
            color: '#1b1b1b'

        MDBoxLayout:
            id: main_scroll
            orientation: "vertical"
            spacing: 25
            adaptive_height: True
            pos_hint: {'center_x': .5, 'center_y': .4}

            MDLabel:
                id: question_output1
                text: "L"
                halign: 'center'
                pos_hint: {'center_x': 0.5, 'center_y': 0.5}
                text_color: '#6183e2'
                size_hint_x: 0.95

            MDTextField: #TextField 1
                mode: "outlined"
                pos_hint: {'center_x': 0.5, 'center_y': 0.35}
                size_hint_x: 0.8
                id: Q1A

                MDTextFieldLeadingIcon:
                    icon: "numeric-1"

            MDLabel:
                id: question_output2
                text: "L"
                halign: 'center'
                pos_hint: {'center_x': 0.5, 'center_y': 0.5}
                text_color: '#6183e2'
                size_hint_x: 0.95

            MDTextField: #TextField 2
                mode: "outlined"
                pos_hint: {'center_x': 0.5, 'center_y': 0.30}
                size_hint_x: 0.8
                id: Q2A

                MDTextFieldLeadingIcon:
                    icon: "numeric-2"


            MDLabel:
                id: question_output3
                text: "L"
                halign: 'center'
                pos_hint: {'center_x': 0.5, 'center_y': 0.5}
                text_color: '#6183e2'
                size_hint_x: 0.95

            MDTextField: #TextField 3
                mode: "outlined"
                pos_hint: {'center_x': 0.5, 'center_y': 0.25}
                size_hint_x: 0.8
                id: Q3A

                MDTextFieldLeadingIcon:
                    icon: "numeric-3"


            MDLabel:
                id: question_output4
                text: "L"
                halign: 'center'
                pos_hint: {'center_x': 0.5, 'center_y': 0.5}
                text_color: '#6183e2'
                size_hint_x: 0.95

            MDTextField: #TextField 4
                mode: "outlined"
                pos_hint: {'center_x': 0.5, 'center_y': 0.20}
                size_hint_x: 0.8
                id: Q4A

                MDTextFieldLeadingIcon:
                    icon: "numeric-4"


            MDLabel:
                id: question_output5
                text: "L"
                halign: 'center'
                pos_hint: {'center_x': 0.5, 'center_y': 0.5}
                text_color: '#6183e2'
                size_hint_x: 0.95

            MDTextField: #TextField 5
                mode: "outlined"
                pos_hint: {'center_x': 0.5, 'center_y': 0.15}
                size_hint_x: 0.8
                id: Q5A

                MDTextFieldLeadingIcon:
                    icon: "numeric-5"


        MDButton:
            pos_hint: {'center_x': 0.5, 'center_y': 0.05}
            on_release: root.PlayPrompt()

            MDButtonIcon:
                icon: 'play'

            MDButtonText:
                text: 'Play Audio'

        MDButton:
            pos_hint: {'center_x': 0.1, 'center_y': 0.075}
            on_release: root.SubmitAnswers()

            MDButtonIcon:
                icon: 'chevron-right'

    MDScreen:   #RESPONSE
        id:ResponseScreen
        name:'ResponseScreen'

        MDLabel:
            id: prompt_output2
            text: "L"
            halign: 'center'
            pos_hint: {'center_x': 0.5, 'center_y': 0.85}
            text_color: '#6183e2'
            size_hint_x: 0.95

        MDDivider: #Horizontal Divider
            size_hint_x: 1
            pos_hint: {'center_x': .5, 'center_y': 0.6}
            color: '#1b1b1b'

        MDBoxLayout:
            id: main_scroll
            orientation: "vertical"
            spacing: 25
            adaptive_height: True
            pos_hint: {'center_x': .5, 'center_y': .4}

            MDCard:
                style: "elevated"
                pos_hint: {"center_x": .5, "center_y": .5}
                padding: "4dp"
                size_hint: None, None
                size: "400dp", "50"

                MDLabel:
                    id:Q1OriginalQuestion
                    text: "L"
                    text_color: '#6183e2'
                    size_hint_x: 0.95
                    halign: 'center'
                    pos_hint: {"center_x": 0.5, "center_y": 0.5}

                MDLabel:
                    id:Q1OriginalAnswer
                    text: "L"
                    text_color: '#6183e2'
                    size_hint_x: 0.95
                    halign: 'center'
                    pos_hint: {"center_x": 0.5, "center_y": 0.5}

            MDCard:
                style: "elevated"
                pos_hint: {"center_x": .5, "center_y": .5}
                padding: "4dp"
                size_hint: None, None
                size: "400dp", "50dp"

                MDLabel:
                    id:Q2OriginalQuestion
                    text: "L"
                    text_color: '#6183e2'
                    size_hint_x: 0.95
                    halign: 'center'
                    pos_hint: {"center_x": 0.5, "center_y": 0.5}
                    
                MDLabel:
                    id:Q2OriginalAnswer
                    text: "L"
                    text_color: '#6183e2'
                    size_hint_x: 0.95
                    halign: 'center'
                    pos_hint: {"center_x": 0.5, "center_y": 0.5}

            MDCard:
                style: "elevated"
                pos_hint: {"center_x": .5, "center_y": .5}
                padding: "4dp"
                size_hint: None, None
                size: "400dp", "50dp"

                MDLabel:
                    id:Q3OriginalQuestion
                    text: "L"
                    text_color: '#6183e2'
                    size_hint_x: 0.95
                    halign: 'center'
                    pos_hint: {"center_x": 0.5, "center_y": 0.5}
                    
                MDLabel:
                    id:Q3OriginalAnswer
                    text: "L"
                    text_color: '#6183e2'
                    size_hint_x: 0.95
                    halign: 'center'
                    pos_hint: {"center_x": 0.5, "center_y": 0.5}

            MDCard:
                style: "elevated"
                pos_hint: {"center_x": .5, "center_y": .5}
                padding: "4dp"
                size_hint: None, None
                size: "400dp", "50dp"

                MDLabel:
                    id:Q4OriginalQuestion
                    text: "L"
                    text_color: '#6183e2'
                    size_hint_x: 0.95
                    halign: 'center'
                    pos_hint: {"center_x": 0.5, "center_y": 0.5}
                    
                MDLabel:
                    id:Q4OriginalAnswer
                    text: "L"
                    text_color: '#6183e2'
                    size_hint_x: 0.95
                    halign: 'center'
                    pos_hint: {"center_x": 0.5, "center_y": 0.5}


            MDCard:
                style: "elevated"
                pos_hint: {"center_x": .5, "center_y": .5}
                padding: "4dp"
                size_hint: None, None
                size: "400dp", "50dp"

                MDLabel:
                    id:Q5OriginalQuestion
                    text: "L"
                    text_color: '#6183e2'
                    size_hint_x: 0.95
                    halign: 'center'
                    pos_hint: {"center_x": 0.5, "center_y": 0.5}
                    
                MDLabel:
                    id:Q5OriginalAnswer
                    text: "L"
                    text_color: '#6183e2'
                    size_hint_x: 0.95
                    halign: 'center'
                    pos_hint: {"center_x": 0.5, "center_y": 0.5}

        MDButton:
            pos_hint: {'center_x': 0.1, 'center_y': 0.075}
            on_release: root.BackToStart()

            MDButtonIcon:
                icon: 'chevron-right'

    MDScreen:   #LOADING
        id:LoadingScreen
        name:'LoadingScreen'

        MDLabel:
            id:GenerationID
            text: 'Now Generating Story...'
            size_hint_x: 0.9
            halign: 'center'
            pos_hint: {'center_x': 0.5, 'center_y': 0.8}
            text_color: 'grey'

        Image:
            id: loading_gif
            source:'Loading.gif'
            center: self.parent.center
            size: 300,300
            anim_loop: 100