<HomeScreen>:
    MDLabel:
        text: 'Home Screen'
        halign: 'left'
        text_color: 'purple'

    MDButton:
        pos_hint: {'center_x': 0.5, 'center_y': 0.5}
        on_release: root.manager.current = 'OtherScreen'

        MDButtonIcon:
            icon: 'plus'

        MDButtonText:
            text: 'Go to next screen'
        
<OtherScreen>:
    MDLabel:
        text: 'Other Screen'
        halign: 'left'
        text_color: 'purple'
        
    MDButton:
        pos_hint: {'center_x': 0.5, 'center_y': 0.5}
        on_release: root.manager.current = 'HomeScreen'

        MDButtonIcon:
            icon: 'plus'

        MDButtonText:
            text: 'Go to previous screen'